[package]
name = "websocket-tcp-example"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[[bin]]
name = "websocket-tcp-server"
path = "src/main.rs"

[[bin]]
name = "websocket-tcp-client"
path = "src/client.rs"

[dependencies]
actix = "0.12"
actix-web = "4.0.0-beta.15"
actix-web-actors = "4.0.0-beta.8"
actix-files = "0.6.0-beta.10"
actix-codec = "0.4.1"

rand = "0.7"
bytes = "0.5.3"
byteorder = "1.2"
futures = "0.3"
env_logger = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1"
tokio-util = "0.6.9"
